### ISSUE TITLE
Android 14 

### ISSUE THREAD

**Issue by NLLAPPS** [josesamuel/remoter#14]
Hi, not sure if you have time to add ability to pass flags to [ServiceConnector#connectWithService()](https://github.com/josesamuel/remoter/blob/5e6c1f79fa6a95681b26aaa8d6ae676e79adbcb5/remoter-builder/src/main/java/remoter/builder/ServiceConnector.kt#L91)

Android 14 will introduce [BIND_ALLOW_ACTIVITY_STARTS ](https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions) and caller will need to add BIND_ALLOW_ACTIVITY_STARTS flag to context.bindService() when binding to a service on another app.

**Comment by josesamuel** [comment]
Try with 2.0.5. 

ServiceConnector now has an optional flags. Auto generated kotlin proxy also has these

```
val timeService:ITimeService = ITimeService_Proxy(this, TIME_SERVICE_INTENT, Context.BIND_AUTO_CREATE)
```
