### ISSUE TITLE
@Parcelize - Unresolved reference: CREATOR

### ISSUE THREAD

**Issue by gorbachev-sweatcoin** [josesamuel/remoter#16]
Hi, awesome plugin, but unfortunately it's not working with @Parcelize, as far as I know, there is an issue with CREATOR field. (https://youtrack.jetbrains.com/issue/KT-19853/Parcelize-CREATOR-field-should-be-available-from-code)

And I receive errors in my project `_Stub.kt:260:57 Unresolved reference: CREATOR`

<img width="893" alt="Screenshot 2023-11-28 at 19 36 51" src="https://github.com/josesamuel/remoter/assets/139762959/8a87d217-0dd6-4dc9-ba29-552733cc6294">

Possible solution would be using `kotlinx.parcelize#parcelableCreator<T : Parcelable>` according to the link provided above. 

<img width="875" alt="Screenshot 2023-11-28 at 19 38 07" src="https://github.com/josesamuel/remoter/assets/139762959/06ceb06a-1461-4db2-8dec-3de3f8370d7e">

**Comment by josesamuel** [comment]
Not related to this. @parcelize works if that is setup properly,
