### ISSUE TITLE
Unchecked Exception is swallowed on oneway communication

### ISSUE THREAD

**Issue by St3ffn** [josesamuel/remoter#4]
#### Issue description
Lets assume we two apps, one acts as Server and the other acts as Client for a IPC Oneway call. 
Now the Client performs a Oneway IPC call which includes a callback to the Server. The Server tries to process the request and suddenly produces a unchecked exception (OutOfMemory...). The Remoter Framework is now swallowing the unchecked Exception and the Client still waits for the callback to be called.

#### Steps to reproduce the issue

1. Client calls Server via Oneway call
2. Server produces unchecked exception 
3. Remoter swallows exception and Server continues 

#### What's the expected result?

Unchecked exception in case of a IPC oneway call should be thrown which leads to the death of the App.

#### What's the actual result?

We had a OutOfMemory on the Server side and remoter was the cause that Android wasn't restarting our App because the OutOfMemory wasn't propagated any further. Instead the App got stuck in a unusable state.

**Comment by josesamuel** [comment]
Fixed in 1.2.4
