### ISSUE TITLE
package org.parceler does not exist

### ISSUE THREAD

**Issue by y-a-n-n** [josesamuel/remoter#6]
Hi! Great library.

Just encountered this issue when using remoter for a kotlin interface. I included the library using a kapt annotation processor:

```
implementation 'com.josesamuel:remoter-annotations:1.2.4'
kapt 'com.josesamuel:remoter:1.2.4'
```

The annotation processor runs correctly and generates my proxy and stub, but at compile time throws the error `package org.parceler does not exist` whenever the generated stub tries to call `org.parceler.Parcels.wrap()`.

Adding the following to my build.gradle works around the issue, but shouldn't Parceler be a transitive dependency?

```
implementation 'org.parceler:parceler-api:1.1.12'
kapt 'org.parceler:parceler:1.1.12'
```

**Comment by josesamuel** [comment]
parceler dependency is needed only if any of the parameters in the
interface is a @Parcel. In other cases, it is not needed. That is the
reason why it was not made transitive dependent. I will make it clear in
the document that if a @Parcel is used, this dependency needed to be
manually added.

Thanks!

**Comment by y-a-n-n** [comment]
No problem, thanks for the clarification.
