### ISSUE TITLE
Accessing AIDL file

### ISSUE THREAD

**Issue by Volatile-Memory** [josesamuel/remoter#7]
Is it possible to access the AIDL file that remoter generates from my kotlin interface?

I would like to have access to it so that I can feed it into the Xamarin Android AIDL compiler so that I can have the service be implemented in C#.

**Comment by josesamuel** [comment]
Remoter doesnt generate AIDL files, it is a replacement for it

**Comment by Volatile-Memory** [comment]
Oh, I thought one of the intermediate steps involved in this annotation processor was to create an AIDL file and feed it through the compiler but it appears it's much more straightforward than that. Thank you for the quick reply.

Do you have any suggestions for how I might be able to do this? I know it probably falls out of the scope of this library but I also noticed that you have a lot of experience with async AIDL which might apply to my unique requirements.
