### ISSUE TITLE
Does not work w/ Parcelize

### ISSUE THREAD

**Issue by herriojr** [josesamuel/remoter#8]
Parcelize itself does not generate an accessible CREATOR or writeToParcel in kotlin. For the CREATOR, technically you can create a java helper method to access the CREATOR accessible from the java side, however, I need to look further into the writeToParcel side.

**Comment by josesamuel** [comment]
Please post an example. I have it working fine with @Parcelize kotlin. Just make sure your service interface is also defined in kotlin
